# dependencies

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - aave/protocol-v2@1.0.1


compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
      - '@aave=aave/protocol-v2@1.0.1'

networks:
  development:
    verify: False
  mainnet-fork2:
    verify: False
  kovan:
    verify: True

# wallets
dotenv:
  .env
wallets:
  from_key: ${PRIVATE_KEY}