# dependencies

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - aave/protocol-v2@1.0.1


compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
      - '@aave=aave/protocol-v2@1.0.1'

networks:
  development:
    verify: False
  mainnet-fork2:
    verify: False
    weth_token: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'
    lending_pool_addresses_provider : '0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5'
  kovan:
    verify: True
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
    lending_pool_addresses_provider : '0x88757f2f99175387aB4C6a4b3067c77A695b0349'

# wallets
dotenv:
  .env
wallets:
  from_key: ${PRIVATE_KEY}